import Head from 'next/head'
import { useContext, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { UserContext } from '../contexts/user.context'

export default function Home({ token_data }) {
	const { setToken } = useContext(UserContext);

	useEffect(() => {
		setToken(token_data);
	}, [])

	return (
		<div className={styles.container}>
			<Head>
				<title>Digiaccel Quiz App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to Quiz App for Digiaccel
				</h1>

				<p className={styles.description}>
					Created By Deepak Kumar Swami {` `}
					<code className={styles.code}>dkswami1820@gmail.com</code>
				</p>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://www.linkedin.com/in/deepak-kumar-swami-030a25136/"
					target="_blank"
					rel="noopener noreferrer"
				>
					
					<span className={styles.logo}>
						Connect with me on LinkedIn
					</span>
				</a>
			</footer>
		</div>
	)
}

export function getServerSideProps({ req, res }) {
	return { props: { token_data : req.cookies.token || "" } };
}